Enabled PRs from forks (#382)
* Feature/311/enable pr from fork (#379)

* trigger vercel

* Retry Vercel build

* Changed master to main in ci.yml

* Enabled PRs from forks

* Changed main to develop in ci.yml

* Changed master to main in etl_to_neon.yml

* added push to main and db logging

* updated .env example

* omitted postgis version

---------

Co-authored-by: Anna <annagennadinik@gmail.com>

* use .env for pushes (#380)

* use .env for pushes

* fixed a typo

* updated example env

---------

Co-authored-by: AdamFinkle <77808710+AdamFinkle@users.noreply.github.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,11 +3,13 @@ name: CI Pipeline
 on:
   push:
     branches:
-      - master
+      - develop
+      - main
   pull_request:
     types: [opened, synchronize, reopened]
     branches:
-      - master
+      - develop
+      - main
 
 jobs:
   eslint:
@@ -50,15 +52,34 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v4
 
+      - name: Set default fork status
+        run: echo "is_fork=false" >> $GITHUB_ENV        
+
+      - name: Check if pull request from fork
+        id: check_fork
+        if: github.event_name == 'pull_request'
+        run: |
+          run: |
+            if [[ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]]; then
+              echo "is_fork=true" >> $GITHUB_ENV
+            fi
+
+      - name: Use .env.example for forks
+        if: env.is_fork == 'true'
+        run: cp .env.example .env
+
       - name: Get Run ID of Most Recent Successful Run
         id: get_run_id
+        if: env.is_fork != 'true'
         run: |
           response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             "https://api.github.com/repos/sfbrigade/datasci-earthquake/actions/workflows/env_vars.yml/runs?status=completed&conclusion=success")
           run_id=$(echo $response | jq '.workflow_runs[0].id')
           echo "Run ID: $run_id"
           echo "run_id=$run_id" >> $GITHUB_ENV
+
       - name: Download .env Artifact
+        if: env.is_fork != 'true'
         uses: actions/download-artifact@v4
         with:
           name: encrypted-env-file
@@ -67,9 +88,17 @@ jobs:
           run-id: ${{ env.run_id }}
 
       - name: Decrypt .env File
+        if: env.is_fork != 'true'
         run: |
           openssl aes-256-cbc -d -salt -pbkdf2 -k "${{ secrets.ARTIFACT_PASS }}" -in .env.enc -out .env
           echo "Decryption complete"
+
+      - name: Ensure .env exists
+        run: |
+          if [ ! -f .env ]; then
+            echo ".env not found. Falling back to .env.example"
+            cp .env.example .env
+          fi
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
@@ -81,6 +110,7 @@ jobs:
           key: ${{ runner.os }}-buildx-${{ github.sha }}
           restore-keys: |
             ${{ runner.os }}-buildx-
+
       - name: Build Docker Containers
         run: docker compose build
 
@@ -94,6 +124,8 @@ jobs:
           docker ps -a
           echo "Logs for backend:"
           docker logs datasci-earthquake-backend-1 || echo "No logs found"
+          echo "Logs for db:"
+          docker logs my_postgis_db || echo "No logs found"
 
       - name: Run Backend Tests
         run: docker compose run backend pytest backend
