test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -198,30 +198,34 @@ jobs:
       - name: Build Docker Containers
         run: docker compose -f compose.yaml -f compose.ci.yaml build
       
-      - name: Start Services
-        run: docker --debug compose -f compose.yaml -f compose.ci.yaml up -d --wait --wait-timeout 300
+      - run: docker images
+      #- run: docker run postgis-custom
+      #- run: docker run postgis-custom
+      #- run: docker run postgis-custom
+      #- name: Start Services
+      #  run: docker compose -f compose.yaml -f compose.ci.yaml up -d --wait --wait-timeout 300
 
-      - run: docker compose volumes 
-      - run: docker inspect datasci-earthquake-frontend-1
+      #- run: docker compose volumes 
+      #- run: docker inspect datasci-earthquake-frontend-1
 
       #- name: copy stuff
       #  run: docker cp datasci-earthquake-frontend-1:/home/node/.npm/_cacache /home/runner/work/datasci-earthquake/datasci-earthquake/torts
 
-      - name: Docker Backend Logs
-        if: always()
-        run: docker logs datasci-earthquake-backend-1 || echo "No logs found"
+      #- name: Docker Backend Logs
+      #  if: always()
+      #  run: docker logs datasci-earthquake-backend-1 || echo "No logs found"
 
-      - name: Docker DB Logs
-        if: always()
-        run: docker logs my_postgis_db || echo "No logs found"
+      #- name: Docker DB Logs
+      #  if: always()
+      #  run: docker logs my_postgis_db || echo "No logs found"
 
       #- name: Docker DB Test (unit tests) Logs
       #  if: always()
       #  run: docker logs my_postgis_db_test || echo "No logs found"
 
-      - name: Docker Frontend Logs
-        if: always()
-        run: docker logs datasci-earthquake-frontend-1 || echo "No logs found"
+      #- name: Docker Frontend Logs
+      #  if: always()
+      #  run: docker logs datasci-earthquake-frontend-1 || echo "No logs found"
 
       #- name: Run Backend Tests
       #  run: docker compose -f compose.yaml -f compose.ci.yaml run --rm backend pytest backend -v
@@ -229,5 +233,5 @@ jobs:
       #- name: Run Frontend Tests
       #  run: docker compose -f compose.yaml -f compose.ci.yaml run --rm frontend npm test
 
-      - name: Clean Up
-        run: docker compose -f compose.yaml -f compose.ci.yaml down
+      #- name: Clean Up
+      #  run: docker compose -f compose.yaml -f compose.ci.yaml down
