added job to create pr into main

diff --git a/.github/workflows/etl_to_neon.yml b/.github/workflows/etl_to_neon.yml
--- a/.github/workflows/etl_to_neon.yml
+++ b/.github/workflows/etl_to_neon.yml
@@ -11,6 +11,7 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       changes: ${{ steps.detect_changes.outputs.changes }}    
+      etl_commit: ${{ steps.detect_changes.outputs.commit_sha }}
 
     steps:
       - name: Checkout repository
@@ -72,6 +73,7 @@ jobs:
           else
             git commit -m "Update datasets (ETL auto-update)"
             echo "changes=true" >> $GITHUB_OUTPUT
+            echo "commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
           fi
 
       - name: Push to develop
@@ -80,20 +82,39 @@ jobs:
           git pull --rebase origin develop
           git push origin HEAD:develop
 
-      - name: Push to new branch for PR into main
-        if: steps.detect_changes.outputs.changes == 'true'
+
+  create-pr:
+    needs: run-etl
+    if: needs.run-etl.outputs.changes == 'true'
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repo to main
+        uses: actions/checkout@v4
+        with:
+          ref: main
+          fetch-depth: 0
+          ssh-key: ${{ secrets.DEPLOY_KEY }}
+
+      - name: Create PR branch and cherry-pick ETL commit
         run: |
           BRANCH="etl/update-${{ github.run_id }}"
-          git checkout -b $BRANCH
+          git fetch origin develop
+          git checkout -b $BRANCH origin/main
+          git cherry-pick ${{ needs.run-etl.outputs.etl_commit }} || {
+            echo "Cherry-pick failed"
+            exit 0 
+          }
           git push origin $BRANCH
+          echo "branch_name=$BRANCH" >> $GITHUB_ENV
 
-      - name: Create Pull Request to Main
+      - name: Create PR to main
         if: steps.detect_changes.outputs.changes == 'true'
         uses: peter-evans/create-pull-request@v6
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           commit-message: "ETL: update GeoJSONs"
-          branch: etl/update-${{ github.run_id }}
+          branch: ${{ env.branch_name }}
           title: "ETL auto-update (GeoJSONs)"
           body: "This PR updates `public/data/*.geojson` files based on the latest ETL run. Please review and merge."
           base: main
